name: esports_now
description: A new Flutter application.


publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  page_transition: "^1.1.7+6"
  chewie: ^1.0.0
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.1
  video_player: ^2.0.2
  firebase_storage: ^8.0.0


  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:



  uses-material-design: true

